/*
    Project Euler, Problem 2
    
    ==========
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:
    
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    Find the sum of all the even-valued terms in the sequence which do not
    exceed four million.
    ==========
    
    Lawrence Velazquez
    1 August 2010
*/

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>


/* Just use macros for constants */
#define PHI   1.61803398874989484820458683436563811772  /* (1 - sqrt 5) / 2 */
#define SQRT5 2.23606797749978969640917366873127623544  /* sqrt 5 */


uint32_t fib(uint32_t n);


int main(int argc, char const *argv[])
{
    /*
        The even-valued Fibonacci numbers are F(0), F(3), F(6), etc. Thus, the
        strategy here is simply to calculate those and add them to a running
        total.
    */
    
    uint64_t even_sum = 0;
    
    uint32_t new_fib;
    
    size_t i = 0;
    while((new_fib = fib(i)) <= 4000000) {
        printf("%d\n", new_fib);
        even_sum += new_fib;
        i += 3;
    }
    
    printf("%lld\n", even_sum);
    return 0;
}


/*
    Computes F(n), the n-th Fibonacci number, using a modification of Binet's
    formula that involves rounding. This closed-form definition is fairly
    quick to calculate, as opposed to the standard recursive definition, which
    usually requires some kind of dynamic programming to have acceptable
    performance.
    
    Returns -1 if n < 0; otherwise, returns the desired Fibonacci number.
*/
uint32_t fib(uint32_t n)
{
    if (n >= 0) {
        return floor(pow(PHI, n) / SQRT5 + 0.5);
    }
    return -1;
}